services:
  db:
    image: postgres:18
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - app-network
    volumes:
      - postgres_data:/data/lib/postgresql
    ports:
      - ${DATABASE_HOST}:${DATABASE_PORT}:${DATABASE_PORT}
    restart: unless-stopped


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: